### ISSUE TITLE
Adding new Context section to ConfigurableTabs fails with ErrorCode: UnableToParseTeamsAppManifest

### ISSUE THREAD

**Issue by matt-psaltis** [OfficeDev/microsoft-teams-app-schema#102]
Our manifest works correctly without the "context" section. When we include the new context section as below, a "Something went wrong" error is displayed.

The zip was uploaded via the "Upload a custom app" link in the Teams apps section as per the documentation on working with the DevPreview schema.

The relevant parts of the manifest are displayed below:

```
  "$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json",
  "manifestVersion": "devPreview",
```

```
  "configurableTabs": [
    {
      "configurationUrl": "https://<redacted>",
      "canUpdateConfiguration": true,
      "scopes": ["team", "groupchat"],
      "context": [
        "channelTab",
        "privateChatTab",
        "meetingChatTab",
        "meetingDetailsTab",
        "meetingSidePanel",
        "meetingStage",
        "callingSidePanel"
      ]
    }
  ]
```

Is this something that is still rolling out to all regions?

The response with headers are included below if the Server Request Id helps with issue identification.

HTTP/1.1 400 Bad Request
Cache-Control: no-cache, no-store
Content-Type: application/json; charset=utf-8
Vary: Origin,Accept-Encoding
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://teams.microsoft.com
X-ServerRequestId: 926B36EEE3D542398363823A987E9EF3
X-MachineName: mtsvc000009
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-MSEdge-Ref: Ref A: 926B36EEE3D542398363823A987E9EF3 Ref B: SYD03EDGE0212 Ref C: 2020-09-01T04:06:45Z
Date: Tue, 01 Sep 2020 04:06:44 GMT
Content-Length: 45

{"errorCode":"UnableToParseTeamsAppManifest"}

**Comment by asnow003** [comment]
This issue had been fixed in the latest versions
