### ISSUE TITLE
Where can I find release log for 1.6 onwards? 

### ISSUE THREAD

**Issue by felipeplets** [OfficeDev/microsoft-teams-app-schema#109]
The releases entries for 1.6, 1.7 and 1.8 are not available in https://github.com/OfficeDev/microsoft-teams-app-schema/releases as specified in the README.md

**Comment by asnow003** [comment]
Sorry there was a lag in updating the release notes.  Let me know if you have any specific questions but if you look a the link for the documentation it goes over all the properties.  The release notes are back and we will work on filling in the gap.  Sorry about the inconvenience.
