### ISSUE TITLE
ConfigurableProperties websiteUrl/developerUrl mixed up

### ISSUE THREAD

**Issue by OliverZeiser** [OfficeDev/microsoft-teams-app-schema#121]
the new configurableProperties contain a property for websiteUrl but in the enum of the schema it is named developerUrl. Something is wrong here....
I am talking about the new 1.10 schema version that was released last night.

**Comment by asnow003** [comment]
@OliverZeiser thanks for the message... let me check with the development team on the naming

**Comment by asnow003** [comment]
@OliverZeiser so sorry on the late response I just noticed I forgot to respond.  Talked with the devlopers on the naming and it was a mistake but probably won't change it.  The docs are up to date though...
