### ISSUE TITLE
Release list not up to date

### ISSUE THREAD

**Issue by MarksPoint** [OfficeDev/microsoft-teams-app-schema#166]
According to this documentation (https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema), the url below should display changes in manifest versions.

https://github.com/OfficeDev/microsoft-teams-app-schema/releases

However, it only shows releases upto v1.12, while the latest version is currently v1.15.

As a developer I'm interested in what changes in these kinds of manifests, so I wonder where the change log is.

**Comment by HiltonGiesenow** [comment]
And we're now up to V1.16, so adding to this voice, please update with changes

**Comment by juna-gupta** [comment]
Release notes are updated.
