### ISSUE TITLE
new devPreview manifest does not default to query

### ISSUE THREAD

**Issue by 01** [OfficeDev/microsoft-teams-app-schema#69]
Since last update to the devPreview manifest the compose extensions commands do not default to "query". It now seems to require explicit setting of "type": "query",

**Comment by tdwhite0** [comment]
I can confirm I had to set this too.

**Comment by MattSFT** [comment]
Are you sure?

https://github.com/OfficeDev/microsoft-teams-app-schema/blob/1c4a16598d50cb7c766cbecee0304825993e661e/MicrosoftTeams.schema.json#L440-L448

**Comment by MattSFT** [comment]
This manifest validates correctly for me:
```json
{
    "$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json",
    "manifestVersion": "devPreview",
    "version": "1.2",
    "id": "0c5cfdbb-596f-4d39-b557-5d9516c94107",
    "packageName": "com.microsoft.teamsdevapp",
    "developer": {
        "name": "Microsoft Corp.",
        "websiteUrl": "https://aka.ms/msteamsdevcenter",
        "privacyUrl": "https://go.microsoft.com/fwlink/?LinkId=512132",
        "termsOfUseUrl": "https://aka.ms/st1pbotttermsofservice"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "Short name",
        "full": "Full nmae"
    },
    "description": {
        "short": "Short description",
        "full": "Full description"
    },
    "accentColor": "#5659AD",
    "composeExtensions": [{
        "botId": "asd",
        "commands": [{
            "type": "action",
            "id": "id",
            "title": "title"
        }]
    }]
}
```

So does this one:
```json
{
    "$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json",
    "manifestVersion": "devPreview",
    "version": "1.2",
    "id": "0c5cfdbb-596f-4d39-b557-5d9516c94107",
    "packageName": "com.microsoft.teamsdevapp",
    "developer": {
        "name": "Microsoft Corp.",
        "websiteUrl": "https://aka.ms/msteamsdevcenter",
        "privacyUrl": "https://go.microsoft.com/fwlink/?LinkId=512132",
        "termsOfUseUrl": "https://aka.ms/st1pbotttermsofservice"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "Short name",
        "full": "Full nmae"
    },
    "description": {
        "short": "Short description",
        "full": "Full description"
    },
    "accentColor": "#5659AD",
    "composeExtensions": [{
        "botId": "asd",
        "commands": [{
            "id": "id",
            "title": "title"
        }]
    }]
}
```

**Comment by tdwhite0** [comment]
I am working on a message extension, using the devPreview for my schema, it was working yesterday without type: "query". When I loaded it up today and updated the manifest, it was just listing my extensions in the box, not letting me query. So I started looking into what might have changed in the schema since yesterday, I saw this issue. I added type: "query" and it was back to normal.

**Comment by tdwhite0** [comment]
The schema was valid each time, the behavior was different.

**Comment by MattSFT** [comment]
You mean the behavior inside of teams changed? That's possible when working on dev preview features. I'll take a look to see whats up.

**Comment by tdwhite0** [comment]
Yes, the behavior inside Teams changed, its as if Teams suddenly started caring whether type: "query" was there instead of defaulting it.

**Comment by MattSFT** [comment]
Yes this is definitely a bug on our side in our parsing logic of the DevPreview schema. It defaults type to "action" instead of "query" if it is not provided. It will take ~2 weeks for us to ship this fix to the public clients. For now, I recommend you specify "type" to query if working on dev preview.

**Comment by tdwhite0** [comment]
OK, sounds good.

**Comment by MattSFT** [comment]
We are planning to make this change temporarily until we can fix this in the client:
https://github.com/OfficeDev/microsoft-teams-app-schema/pull/72/files

**Comment by 01** [comment]
Welp Im late to the conversation, glad to know it wasnt something I was doing.

**Comment by MattSFT** [comment]
This should now be resolved
